package modrinth

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/mclucy/lucy/logger"
	"github.com/mclucy/lucy/slugmap"
	"github.com/mclucy/lucy/types"
)

// TODO: Refactor to separate all API functions to accept an url. While the urls
// are generated by other functions. This will make the code more modular and
// easier to test.

var (
	ENoVersion = errors.New("modrinth version not found")
	ENoProject = errors.New("modrinth project not found")
	ENoMember  = errors.New("modrinth project memberResponse not found")
)

// TODO: This has a chance of causing segmentation faults
func listVersions(slug types.ProjectName) (
	versions []*versionResponse,
	err error,
) {
	tryFetch := func(target types.ProjectName) ([]*versionResponse, error) {
		res, err := http.Get(versionsUrl(target))
		if err != nil {
			return nil, err
		}
		defer res.Body.Close()

		if res.StatusCode != http.StatusOK {
			return nil, ENoProject
		}

		data, err := io.ReadAll(res.Body)
		if err != nil {
			return nil, err
		}

		var out []*versionResponse
		if err := json.Unmarshal(data, &out); err != nil {
			return nil, ENoProject
		}
		return out, nil
	}

	versions, err = tryFetch(slug)
	if err == nil {
		return versions, nil
	}

	if canonical, ok := slugmap.Default().GetLoose(types.SourceModrinth, string(slug)); ok && canonical != string(slug) {
		return tryFetch(types.ProjectName(canonical))
	}

	return nil, err
}

// getVersion is named as so because a Package in lucy is equivalent to a version
// in SourceModrinth.
func getVersion(id types.PackageId) (
	v *versionResponse,
	err error,
) {
	versions, err := listVersions(id.Name)
	if err != nil {
		return nil, err
	}
	if id.Version == types.VersionLatest {
		v, err = latestVersion(id.Name)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
	for _, version := range versions {
		if types.RawVersion(version.VersionNumber) == id.Version &&
			versionSupportsLoader(version, id.Platform) {
			return version, nil
		}
	}
	return nil, ENoVersion
}

func getVersionById(id string) (v *versionResponse, err error) {
	res, err := http.Get(versionUrl(id))
	if err != nil {
		return nil, fmt.Errorf("modrinth: request failed: %w", err)
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusOK {
		return nil, ENoVersion
	}

	data, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, fmt.Errorf("modrinth: failed to read response: %w", err)
	}
	v = &versionResponse{}
	err = json.Unmarshal(data, v)
	if err != nil {
		return nil, ENoVersion
	}
	return
}

func versionSupportsLoader(
	version *versionResponse,
	loader types.Platform,
) bool {
	for _, l := range version.Loaders {
		if types.Platform(l).Satisfy(loader) {
			return true
		}
	}
	return false
}

func latestVersion(slug types.ProjectName) (
	v *versionResponse,
	err error,
) {
	versions, err := listVersions(slug)
	if err != nil {
		return nil, err
	}
	for _, version := range versions {
		if version.VersionType == "release" &&
			(v == nil || version.DatePublished.After(v.DatePublished)) {
			v = version
		}
	}
	if v == nil {
		// No release version found; fall back to the latest pre-release (beta/alpha).
		logger.Info("no release version found for " + slug.Title() + ", falling back to latest pre-release")
		for _, version := range versions {
			if v == nil || version.DatePublished.After(v.DatePublished) {
				v = version
			}
		}
	}
	if v == nil {
		return nil, ENoVersion
	}
	logger.Debug("latest version of " + slug.String() + ": " + v.VersionNumber)
	return v, nil
}

func latestCompatibleVersion(slug types.ProjectName, platform types.Platform) (
	v *versionResponse,
	err error,
) {
	versions, err := listVersions(slug)
	if err != nil {
		return nil, err
	}
	filterByLoader := platform != types.PlatformAny && platform != types.PlatformNone
	for _, version := range versions {
		if filterByLoader && !versionSupportsLoader(version, platform) {
			continue
		}
		if version.VersionType == "release" &&
			(v == nil || version.DatePublished.After(v.DatePublished)) {
			v = version
		}
	}
	if v == nil {
		// No release version found; fall back to the latest pre-release (beta/alpha).
		logger.Info("no compatible version found for " + slug.Title() + ", falling back to latest pre-release")
		for _, version := range versions {
			if filterByLoader && !versionSupportsLoader(version, platform) {
				continue
			}
			if v == nil || version.DatePublished.After(v.DatePublished) {
				v = version
			}
		}
	}
	if v == nil {
		return nil, ENoVersion
	}
	return v, nil
}
